apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: "0.28.x"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  values:
    injector:
      enabled: false
    server:
      standalone:
        enabled: true
      extraConfig: |
        ui = true

        listener "tcp" {
          address     = "0.0.0.0:8200"
          tls_disable = 1
        }

        storage "file" {
          path = "/vault/data"
        }
