apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  values:
    global:
      enabled: true
    server:
      ha:
        enabled: false
      dev:
        enabled: false
      dataStorage:
        enabled: true
      auditStorage:
        enabled: false
      service:
        type: ClusterIP
    injector:
      enabled: true
