apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
      # version: ">=0.28.0 <1.0.0"  # <-- (optional) pin a safe range when you’re ready
  values:
    global:
      enabled: true
    server:
      ha:
        enabled: false          # standalone
      dev:
        enabled: false
      dataStorage:
        enabled: true
      auditStorage:
        enabled: false
      service:
        type: ClusterIP
      # Uncomment to expose via Ingress later:
      # ingress:
      #   enabled: true
      #   ingressClassName: traefik
      #   hosts:
      #     - host: vault.example.local
      #       paths: ["/"]
    injector:
      enabled: true             # webhook for secrets injection
