apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    # Create a public LB so Ingress gets an ADDRESS
    service:
      type: LoadBalancer
    # Use standard Kubernetes Ingress (no CRDs needed)
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik
    # Disable the insecure dashboard by default
    ingressRoute:
      dashboard:
        enabled: false
