apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    providers:
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
          path: "traefik/traefik"
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik
    service:
      type: LoadBalancer
