apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: yaks
  namespace: yaks
spec:
  interval: 5m
  chart:
    spec:
      chart: yaks
      version: "0.19.2"
      sourceRef:
        kind: HelmRepository
        name: yaks
        namespace: flux-system
  values: {}