apiVersion: batch/v1
kind: Job
metadata:
  name: vault-unseal
  namespace: vault
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: vault-unseal
        image: hashicorp/vault:1.17.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            for i in 1 2 3; do
              key=$(cat /keys/key$i)
              vault operator unseal $key || true
            done
        env:
          - name: VAULT_ADDR
            value: http://vault.vault.svc.cluster.local:8200
        volumeMounts:
          - name: unseal-keys
            mountPath: /keys
            readOnly: true
      volumes:
        - name: unseal-keys
          secret:
            secretName: vault-unseal-keys
