apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bank-vaults-operator
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault-operator
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
        namespace: flux-system
      version: "1.21.0"
