apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      # version: "v1.15.x"   # <-- (optional) pin a version when you’re ready
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    # Enable ServiceMonitor if you run Prometheus Operator:
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
