apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: website
spec:
  ingressClassName: traefik
  tls:
    - hosts: [127.0.0.1.sslip.io]
      secretName: website-tls
  rules:
    - host: 127.0.0.1.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
